export { Sim, CAPACITY } from './sim';
export { defaultConfig, mergeConfig } from './config';
export type { SimConfig, DeepPartial } from './config';
export { Flock, MAX_NEIGHBOURS, MAX_CONTACTS } from './flock';
export { Rng } from './rng';
export { Perception } from './perception';
export { Groups } from './groups';
export type { Threat } from './perception';
export { computeMetrics } from './metrics';
export type { Metrics } from './metrics';
export { SheepState, STATE_NAMES, SNAP_HEADER, SNAP_STRIDE, snapshotLength } from './types';
