// Writes web/generated/sheep-glb.ts: the sheep model as base64, imported by the page and the overlay.
// Generated rather than committed so assets/sheep.glb stays the single source of truth.
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';

const SRC = 'assets/sheep.glb';
const OUT = 'web/generated/sheep-glb.ts';
mkdirSync('web/generated', { recursive: true });
// Skip the rewrite when it is already current, but never skip the staleness check: an out-of-date
// embed silently ships the previous model, which is invisible until you inspect the scene graph.
try {
  if (statSync(OUT).mtimeMs > statSync(SRC).mtimeMs) process.exit(0);
} catch { /* not generated yet */ }
const glb = readFileSync(SRC).toString('base64');
writeFileSync(OUT, `// generated by tools/gen-glb.mjs from ${SRC}\nexport const SHEEP_GLB_BASE64 = '${glb}';\n`);
console.log(`embedded ${SRC} (${(glb.length / 1024).toFixed(0)} KB base64)`);
