// Writes web/generated/sheep-glb.ts: the sheep model as base64, imported by the page and the overlay.
// Generated rather than committed so assets/sheep.glb stays the single source of truth.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
mkdirSync('web/generated', { recursive: true });
const glb = readFileSync('assets/sheep.glb').toString('base64');
writeFileSync('web/generated/sheep-glb.ts', `// generated by tools/gen-glb.mjs from assets/sheep.glb\nexport const SHEEP_GLB_BASE64 = '${glb}';\n`);
